/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#0f131c',
        'surface-dim': '#0f131c',
        'surface-bright': '#353942',
        'surface-container-lowest': '#0a0e16',
        'surface-container-low': '#181c24',
        'surface-container': '#1c2028',
        'surface-container-high': '#262a33',
        'surface-container-highest': '#31353e',
        'surface-variant': '#31353e',
        'on-surface': '#dfe2ee',
        'on-surface-variant': '#bbc9cf',
        'inverse-surface': '#dfe2ee',
        'inverse-on-surface': '#2c3039',
        'outline': '#859399',
        'outline-variant': '#3c494e',
        'surface-tint': '#47d6ff',
        'primary': '#a5e7ff',
        'on-primary': '#003543',
        'primary-container': '#00d2ff',
        'on-primary-container': '#00566a',
        'inverse-primary': '#00677f',
        'secondary': '#d0bcff',
        'on-secondary': '#3c0091',
        'secondary-container': '#571bc1',
        'on-secondary-container': '#c4abff',
        'tertiary': '#69f6b9',
        'on-tertiary': '#003824',
        'tertiary-container': '#48d99e',
        'on-tertiary-container': '#005b3d',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#b6ebff',
        'primary-fixed-dim': '#47d6ff',
        'on-primary-fixed': '#001f28',
        'on-primary-fixed-variant': '#004e60',
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#d0bcff',
        'on-secondary-fixed': '#23005c',
        'on-secondary-fixed-variant': '#5516be',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        'background': '#0f131c',
        'on-background': '#dfe2ee',
        // Gaming Tactical Mech / Armor Theme (Red / Stealth Slate / Carbon Black)
        'gaming-bg': '#08090c',
        'gaming-carbon': '#0d0e13',
        'gaming-panel': '#151720',
        'gaming-panel-high': '#1c1f2b',
        'gaming-panel-highest': '#25293a',
        'gaming-border': '#2d3346',
        'gaming-red': '#ff0038',
        'gaming-red-bright': '#ff2a55',
        'gaming-red-glow': 'rgba(255, 0, 56, 0.45)',
        'gaming-red-dark': '#8a001e',
        'gaming-red-subtle': 'rgba(255, 0, 56, 0.12)',
        'gaming-accent': '#ff1a40',
        'gaming-slate': '#8a93a8',
        'gaming-white': '#f8fafc',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        '2xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'gutter': '1rem',
        'gutter-desktop': '1.5rem',
        'margin': '1rem',
        'margin-tablet': '1.5rem',
        'margin-desktop': '2.5rem',
      },
      fontFamily: {
        'display': ['Space Grotesk', 'sans-serif'],
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-lg': ['JetBrains Mono', 'monospace'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'display-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
      },
      fontWeight: {
        'header': '700',
        'subheader': '500',
        'body': '400',
        'bold': '700',
        'medium': '500',
        'normal': '400',
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
